### ISSUE TITLE
Add an Accordion Component

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [parthasdey2304/React-Components#12]
Hi @parthasdey2304 ,

I want to contribute an Accordion Component in your repository.
Please assign this task to me...

And please don't forget to label this issue as **hacktoberfest2024**. So, this contribution is marked under Hacktoberfest.

Thank You

**Comment by parthasdey2304** [comment]
You have been assigned @Abhiraj-Sardar

**Comment by Abhiraj-Sardar** [comment]
Hi @parthasdey2304 ,

I Just made a Pull Request.

This is how the component look like---

![Screenshot 2024-10-03 124708](https://github.com/user-attachments/assets/83539a27-ded1-45c7-8e2a-8b67f208d581)

Now You can close this issue.
